name: Deploy Infrastructure and App to AWS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  TF_VAR_gemini_api_key: ${{ secrets.GEMINI_API_KEY }}

jobs:
  provision-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Extract AWS Account ID
        id: account
        run: echo "id=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push frontend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO: campusfix-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build --build-arg VITE_API_URL=/ -t $ECR_REGISTRY/$REPO:$IMAGE_TAG -t $ECR_REGISTRY/$REPO:latest -f frontend/Dockerfile frontend/
          docker push $ECR_REGISTRY/$REPO --all-tags

      - name: Build, tag, and push backend image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO: campusfix-backend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$REPO:$IMAGE_TAG -t $ECR_REGISTRY/$REPO:latest -f backend/Dockerfile .
          docker push $ECR_REGISTRY/$REPO --all-tags

      - name: Force ECS Update
        run: |
          aws ecs update-service --cluster campusfix-cluster --service campusfix-service --force-new-deployment --region ${{ env.AWS_REGION }}
